// <auto-generated />
namespace Sigedap.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AgregandoActaDestruir : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregandoActaDestruir));
        
        string IMigrationMetadata.Id
        {
            get { return "201604221501436_AgregandoActaDestruir"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
