//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sigedap.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ProrrogaGarantiaInterna
	{
		public virtual int Id
		{
			get;
			set;
		}

		public virtual System.DateTime Fecha
		{
			get;
			set;
		}

		public virtual string ElaboradoPor
		{
			get;
			set;
		}

		public virtual string AprobadoPor
		{
			get;
			set;
		}

	}
}

